import { Logo } from "./_ui/logo";
import { Navigation } from "./_ui/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <header>
          <Logo />
          <Navigation />
        </header>

        {children}
      </body>
    </html>
  );
}
